# Generated by Django 3.2.1 on 2022-06-09 08:48

from django.db import migrations


def fix_trip_tourists(apps, schema_editor):
    """Исправляем ошибку в турах, из-за которой некоторые туристы могли не добавиться в список Trip.tourists."""
    # We can't import the Trip model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Trip = apps.get_model('main', 'Trip')
    for trip in Trip.objects.all():
        for company in trip.trip_companies.all():
            for tourist in company.tourists.all():
                if not trip.tourists.filter(pk=tourist.pk).exists():
                    trip.tourists.add(tourist)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_prices_non_negative'),
    ]

    operations = [
        migrations.RunPython(fix_trip_tourists, elidable=True),
    ]
