# Generated by Django 3.2.1 on 2022-06-09 11:23

from django.db import migrations, models
import django.db.models.deletion
import main.models.agency.agency_employee_avatar


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_fix_trip_tourists_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyEmployeeAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.utils.file_upload_path, verbose_name='Аватар')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='main.agencyemployee')),
            ],
            options={
                'verbose_name': 'Аватар сотрудника',
                'verbose_name_plural': 'Аватары сотрудников',
            },
        ),
    ]
