# Generated by Django 3.2.1 on 2022-06-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_tripworker_permission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personidentitydocument',
            name='main_personidentitydocument_is_unique',
        ),
    ]
