# Generated by Django 3.2.1 on 2022-06-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_is_food_included_change_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='is_food_included',
            new_name='is_food_preferences_used',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='is_food_included',
            new_name='is_food_preferences_used',
        ),
    ]
