# Generated by Django 3.2.1 on 2022-07-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_is_food_included_rename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelprebooking',
            old_name='change_freeze_period',
            new_name='free_cancel_period',
        ),
    ]
