# Generated by Django 3.2.1 on 2022-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_hotelprebooking_change_freeze_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprebooking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Предварительная'), (1, 'Подтверждённая'), (2, 'Реализованная')], null=True, verbose_name='Статус'),
        ),
    ]
