# Generated by Django 3.2.1 on 2023-02-17 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_add_trip_money_stat_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='tourists_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество гостей'),
        ),
        migrations.AddField(
            model_name='tripcompany',
            name='expected_tourists_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ожидаемое количество гостей'),
        ),
    ]
