# Generated by Django 3.2.1 on 2023-04-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_trip_company_supplier_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemedia',
            name='original_file_name',
            field=models.CharField(editable=False, max_length=256, verbose_name='Исходное имя файла'),
        ),
        migrations.AlterField(
            model_name='tripmedia',
            name='original_file_name',
            field=models.CharField(editable=False, max_length=256, verbose_name='Исходное имя файла'),
        ),
    ]
