# Generated by Django 3.2.1 on 2023-04-17 15:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_media_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePaymentParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя/название')),
            ],
            options={
                'verbose_name': 'Платёж - участник',
                'verbose_name_plural': 'Платежи - участники',
            },
        ),
        migrations.CreateModel(
            name='BasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Дата платежа')),
                ('is_incoming', models.BooleanField(verbose_name='Входящий платёж')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('purpose_text', models.CharField(max_length=128, verbose_name='Назначение (текст)')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.agency')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to='main.person')),
                ('parent_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_payments', to='main.basepayment')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_payments', to='main.basepaymentparty')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_payments', to='main.basepaymentparty')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_payments', to='main.trip')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='TripServicePayment',
            fields=[
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='trip_service_payment', serialize=False, to='main.basepayment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_service_payments', to='main.tripandservice')),
            ],
            options={
                'verbose_name': 'Платёж за услугу',
                'verbose_name_plural': 'Платежи за услуги',
            },
            bases=('main.basepayment',),
        ),
        migrations.CreateModel(
            name='SupplierPaymentParty',
            fields=[
                ('payment_party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='supplier_payment_party', serialize=False, to='main.basepaymentparty')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_party_links', to='main.supplier')),
            ],
            options={
                'verbose_name': 'Платёж - участник - контрагент',
                'verbose_name_plural': 'Платежи - участники - контрагенты',
            },
            bases=('main.basepaymentparty',),
        ),
        migrations.CreateModel(
            name='PersonPaymentParty',
            fields=[
                ('payment_party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='person_payment_party', serialize=False, to='main.basepaymentparty')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_party_links', to='main.person')),
            ],
            options={
                'verbose_name': 'Платёж - участник - человек',
                'verbose_name_plural': 'Платежи - участники - люди',
            },
            bases=('main.basepaymentparty',),
        ),
        migrations.CreateModel(
            name='HotelPayment',
            fields=[
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='hotel_payment', serialize=False, to='main.basepayment')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_payments', to='main.hotelprebooking')),
            ],
            options={
                'verbose_name': 'Платёж за услугу',
                'verbose_name_plural': 'Платежи за услуги',
            },
            bases=('main.basepayment',),
        ),
        migrations.CreateModel(
            name='ClientContractPayment',
            fields=[
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='client_contract_payment', serialize=False, to='main.basepayment')),
                ('client_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contract_payments', to='main.clientcontract')),
            ],
            options={
                'verbose_name': 'Платёж по тур. договору',
                'verbose_name_plural': 'Платежи по тур. договорам',
            },
            bases=('main.basepayment',),
        ),
    ]
