# Generated by Django 3.2.1 on 2023-04-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripservicepayment',
            old_name='service',
            new_name='trip_and_service',
        ),
        migrations.AlterField(
            model_name='personpaymentparty',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_party_links', to='main.person'),
        ),
        migrations.AlterField(
            model_name='supplierpaymentparty',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_party_links', to='main.supplier'),
        ),
    ]
