# Generated by Django 3.2.1 on 2023-04-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_payments_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepayment',
            name='is_incoming',
            field=models.BooleanField(default=False, verbose_name='Входящий платёж'),
        ),
    ]
