# Generated by Django 3.2.1 on 2023-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_payment_purpose_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.CharField(choices=[(None, '(Категория)'), ('REGULAR', 'Регулярный'), ('INDIVIDUAL', 'Индивидуальный'), ('CORPORATE', 'Корпоративный')], default='REGULAR', max_length=16, verbose_name='Категория'),
        ),
    ]
