# Generated by Django 3.2.1 on 2023-08-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_demorequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
