# Generated by Django 3.2.1 on 2024-01-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_bankdetails_correspondent_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidecabinetlink',
            name='cabinet_id',
        ),
        migrations.AlterField(
            model_name='guidecabinetlink',
            name='short_cabinet_id',
            field=models.CharField(max_length=16, unique=True, verbose_name='Ссылка - ID кабинета'),
        ),
    ]
