# Generated by Django 3.2.1 on 2024-02-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_set_trip_is_visible_for_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_created_by_external_user',
            field=models.BooleanField(default=False, verbose_name='Самозапись'),
        ),
        migrations.AddField(
            model_name='tripcompany',
            name='is_created_by_external_user',
            field=models.BooleanField(default=False, verbose_name='Самозапись'),
        ),
        migrations.AddField(
            model_name='tripcompany',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик/Заявка'),
        ),
    ]
