# Generated by Django 3.2.1 on 2024-02-02 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_adding_clients_externally'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Комиссия по умолчанию'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_commission_type',
            field=models.PositiveSmallIntegerField(choices=[(None, '(Выберите вид комиссии)'), (1, 'Фиксированная (в рублях)'), (2, 'В % от суммы договора')], default=2, verbose_name='Вид комиссии по умолчанию'),
        ),
    ]
