# Generated by Django 3.2.1 on 2024-02-15 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_set_trip_is_visible_for_suppliers_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCabinetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_id', models.CharField(max_length=16, unique=True, verbose_name='ID кабинета')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('supplier_cabinet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_cabinet', to='main.suppliercabinetlink')),
            ],
            options={
                'verbose_name': 'Ссылка для самозаписи',
                'verbose_name_plural': 'Ссылки для самозаписи',
            },
        ),
    ]
