# Generated by Django 3.2.1 on 2024-04-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_route_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcompany',
            name='has_children_pre7',
            field=models.BooleanField(default=False, verbose_name='Дети до 7 лет'),
        ),
    ]
