# Generated by Django 3.2.1 on 2024-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_tripcompany_has_children_pre7'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
