# Generated by Django 3.2.1 on 2024-04-18 13:51

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_service_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPaymentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_system', models.PositiveSmallIntegerField(choices=[(1, 'ЮKassa')], verbose_name='Платёжная система')),
                ('account_id', models.CharField(max_length=128, verbose_name='Идентификатор магазина')),
                ('secret_key', django_cryptography.fields.encrypt(models.CharField(max_length=128, verbose_name='Секретный ключ'))),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_token', to='main.agency')),
            ],
            options={
                'verbose_name': 'Ключ доступа к платёжной системе',
                'verbose_name_plural': 'Ключи доступа к платёжным системам',
            },
        ),
    ]
