# Generated by Django 3.2.1 on 2024-04-26 13:46

from django.db import migrations
import main.models.fields.random_slug_field


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_add_agency_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='slug',
            field=main.models.fields.random_slug_field.RandomSlugField(blank=True, editable=False, unique=True, verbose_name='Строковый идентификатор'),
        ),
    ]
