# Generated by Django 3.2.1 on 2024-04-26 15:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_clientcontract_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=128, verbose_name='Идентификатор платежа')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('client_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_payments', to='main.clientcontract')),
                ('payment_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_payments', to='main.agencypaymenttoken')),
            ],
            options={
                'verbose_name': 'Неподтверждённый платёж',
                'verbose_name_plural': 'Неподтверждённые платежи',
            },
        ),
    ]
