# Generated by Django 3.2.1 on 2024-05-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_agencysocialnetworkcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencysocialnetworkcontact',
            name='social_network',
            field=models.CharField(choices=[(None, '(Выберите социальную сеть)'), ('VK', 'ВКонтакте'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('SKYPE', 'Skype'), ('INSTAGRAM', 'Instagram'), ('OPEN_LINE', 'Открытая линия'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Другое')], max_length=16, verbose_name='Социальная сеть'),
        ),
        migrations.AlterField(
            model_name='legalsuppliersocialnetworkcontact',
            name='social_network',
            field=models.CharField(choices=[(None, '(Выберите социальную сеть)'), ('VK', 'ВКонтакте'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('SKYPE', 'Skype'), ('INSTAGRAM', 'Instagram'), ('OPEN_LINE', 'Открытая линия'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Другое')], max_length=16, verbose_name='Социальная сеть'),
        ),
        migrations.AlterField(
            model_name='personsocialnetworkcontact',
            name='social_network',
            field=models.CharField(choices=[(None, '(Выберите социальную сеть)'), ('VK', 'ВКонтакте'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('SKYPE', 'Skype'), ('INSTAGRAM', 'Instagram'), ('OPEN_LINE', 'Открытая линия'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Другое')], max_length=16, verbose_name='Социальная сеть'),
        ),
    ]
