# Generated by Django 3.2.1 on 2024-07-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_agency_is_supplier_cabinet_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name': 'Банк', 'verbose_name_plural': 'Банки'},
        ),
        migrations.AlterModelOptions(
            name='bankmoneyaccount',
            options={'verbose_name': 'Денежный счёт (безналичный)', 'verbose_name_plural': 'Денежные счета (безналичные)'},
        ),
        migrations.AlterModelOptions(
            name='basemoneyaccount',
            options={'verbose_name': 'Денежный счёт (базовый)', 'verbose_name_plural': 'Денежные счета (базовые)'},
        ),
        migrations.AlterModelOptions(
            name='cashmoneyaccount',
            options={'verbose_name': 'Денежный счёт (для наличных расчётов)', 'verbose_name_plural': 'Денежные счета (для наличных расчётов)'},
        ),
        migrations.AlterModelOptions(
            name='departurepoint',
            options={'verbose_name': 'Место сбора группы', 'verbose_name_plural': 'Места сбора групп'},
        ),
        migrations.AlterModelOptions(
            name='inboxidentitydocument',
            options={'verbose_name': 'Удостоверение личности в анкете', 'verbose_name_plural': 'Удостоверения личности в анкетах клиентов'},
        ),
        migrations.AlterModelOptions(
            name='inboxphonecontact',
            options={'verbose_name': 'Телефон в анкете', 'verbose_name_plural': 'Телефоны в анкетах клиентов'},
        ),
        migrations.AlterModelOptions(
            name='inboxregistrationdata',
            options={'verbose_name': 'Адрес и дата регистрации в анкете', 'verbose_name_plural': 'Адреса и даты регистрации в анкетах клиентов'},
        ),
        migrations.AlterModelOptions(
            name='demorequest',
            options={'verbose_name': 'Запрос демо доступа', 'verbose_name_plural': 'Запросы демо доступа'},
        ),
    ]
