# Generated by Django 3.2.1 on 2024-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_trip_auto_update_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='days_after_trip_to_show_details_for_guide',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Сколько дней после окончания тура гид видит список группы и другие детали'),
        ),
        migrations.AddField(
            model_name='agency',
            name='days_before_trip_to_show_details_for_guide',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='За сколько дней до начала тура гид видит список группы и другие детали'),
        ),
        migrations.AddField(
            model_name='agency',
            name='max_days_to_edit_finished_trips',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Сколько дней после окончания тура разрешается его редактировать'),
        ),
    ]
