# Generated by Django 3.2.1 on 2022-06-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial_squashed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='city',
            name='main_city_name_is_unique',
        ),
        migrations.RemoveConstraint(
            model_name='hotel',
            name='main_hotel_name_is_unique',
        ),
        migrations.RemoveConstraint(
            model_name='restaurant',
            name='main_restaurant_name_is_unique',
        ),
        migrations.AddField(
            model_name='city',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.agency'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='main.agency'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='main.agency'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('agency', 'name', 'region', 'country'), name='main_city_name_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(fields=('agency', 'city', 'name'), name='main_hotel_name_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('agency', 'city', 'name'), name='main_restaurant_name_is_unique'),
        ),
    ]
