# Generated by Django 3.2.1 on 2022-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_personidentitydocument_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidecabinetlink',
            name='short_cabinet_id',
            field=models.CharField(default='', max_length=16, unique=True, verbose_name='Ссылка - ID кабинета (укороченная)'),
            preserve_default=False,  # Тут проходит default='', т.к. кабинеты нигде пока не добавлялись
        ),
        migrations.AlterField(
            model_name='guidecabinetlink',
            name='cabinet_id',
            field=models.CharField(max_length=256, unique=True, verbose_name='Ссылка - ID кабинета'),
        ),
    ]
