# Generated by Django 3.2.1 on 2022-06-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_triproommatesgroup_is_room_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_food_included',
            field=models.BooleanField(default=True, verbose_name='Питание на маршруте'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_food_included',
            field=models.BooleanField(default=True, verbose_name='Питание на маршруте'),
        ),
    ]
