# Generated by Django 3.2.1 on 2022-10-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_hotelprebooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='main.supplier'),
        ),
    ]
