# Generated by Django 3.2.1 on 2022-10-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_client_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyemployee',
            options={'permissions': [('manage_employees', 'Пользователь может управлять сотрудниками агентства (#наше)')], 'verbose_name': 'Сотрудник агентства', 'verbose_name_plural': 'Сотрудники агентств'},
        ),
    ]
