# Generated by Django 3.2.1 on 2023-02-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_company_and_contract_tourists_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='contract_template',
            field=models.CharField(blank=True, max_length=128, verbose_name='Шаблон договора'),
        ),
    ]
