# Generated by Django 3.2.1 on 2023-04-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_basepayment_is_incoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepayment',
            name='comment',
            field=models.CharField(blank=True, max_length=256, verbose_name='Дополнительный комментарий'),
        ),
    ]
