# Generated by Django 3.2.1 on 2023-04-24 11:55

from django.db import migrations, models
import django.db.models.deletion
import main.models.money.payment_media


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_basepayment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(editable=False, max_length=256, verbose_name='Исходное имя файла')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Описание')),
                ('file', models.FileField(upload_to=main.models.utils.file_upload_path, verbose_name='Файл')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_media_files', to='main.basepayment')),
            ],
            options={
                'verbose_name': 'Медиафайл к платежу',
                'verbose_name_plural': 'Медиафайлы к платежам',
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmedia',
            constraint=models.UniqueConstraint(fields=('payment', 'file'), name='main_paymentmedia_is_unique'),
        ),
    ]
