# Generated by Django 3.2.1 on 2023-05-04 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_payment_refactoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_payments', to='main.basepaymentparty'),
        ),
    ]
