# Generated by Django 3.2.1 on 2023-05-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_payment_recipient_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelexpenseitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_expense_items', to='main.hotelprebooking'),
        ),
    ]
