# Generated by Django 3.2.1 on 2023-07-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_suppliercommissionexpenseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose_text',
            field=models.CharField(max_length=256, verbose_name='Назначение (текст)'),
        ),
    ]
