# Generated by Django 3.2.1 on 2023-08-02 13:59

from django.db import migrations


def delete_agency_admins(apps, schema_editor):
    """Удаляем группу пользователей agency_admins, вместо которой теперь будет team_leaders."""
    # We can't import the Group model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Group = apps.get_model('auth', 'group')
    admins_group = Group.objects.filter(name="agency_admins").first()
    if admins_group:
        users = admins_group.user_set.all()
        for user in users:
            user.groups.add(*Group.objects.filter(name__in=["sales_managers", "service_guides", "trip_planners"]))
        admins_group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_delete_trip_permission'),
    ]

    operations = [
        migrations.RunPython(delete_agency_admins, elidable=True),
    ]
