# Generated by Django 3.2.1 on 2023-09-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_demorequest_part2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientcontract',
            name='main_clientcontract_is_unique',
        ),
    ]
