# Generated by Django 3.2.1 on 2023-10-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_clientcontract_is_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('manage_clients', 'Пользователь может управлять персональными данными гостей, но не удалять их (#наше)'), ('delete_clients', 'Пользователь может удалять гостей (#наше)'), ('export_clients', 'Пользователь может экспортировать персональные данные гостей (#наше)')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'permissions': [('manage_coupons', 'Пользователь может управлять промокодами и сертификатами (#наше)')], 'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
    ]
