# Generated by Django 3.2.1 on 2023-10-31 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_client_and_coupon_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bik', models.CharField(max_length=9, unique=True)),
                ('correspondent_account', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BaseMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agency')),
            ],
            options={
                'unique_together': {('name', 'agency')},
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='main.basemoneyaccount'),
        ),
        migrations.CreateModel(
            name='CashMoneyAccount',
            fields=[
                ('basemoneyaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemoneyaccount')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.person')),
            ],
            bases=('main.basemoneyaccount',),
        ),
        migrations.CreateModel(
            name='BankMoneyAccount',
            fields=[
                ('basemoneyaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemoneyaccount')),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bankdetails')),
            ],
            bases=('main.basemoneyaccount',),
        ),
    ]
