# Generated by Django 3.2.1 on 2023-11-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20231031_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripworker',
            name='money_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_workers', to='main.basemoneyaccount'),
        ),
    ]
