# Generated by Django 3.2.1 on 2023-11-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_tripworker_money_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemoneyaccount',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
