# Generated by Django 3.2.1 on 2023-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_basemoneyaccount_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='correspondent_account',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
