# Generated by Django 3.2.1 on 2024-01-11 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_guide_cabinet_long_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidecabinetlink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
