# Generated by Django 3.2.1 on 2024-01-11 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_guidecabinetlink_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestFormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16, unique=True, verbose_name='Токен')),
                ('guest_count', models.PositiveSmallIntegerField(verbose_name='Количество гостей')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('trip_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_form_link', to='main.tripcompany')),
            ],
            options={
                'verbose_name': 'Ссылка на анкету гостя (гостей)',
                'verbose_name_plural': 'Ссылки на анкеты гостей',
            },
        ),
    ]
