# Generated by Django 3.2.1 on 2024-01-25 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_guestformlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': [('manage_suppliers', 'Пользователь может управлять контрагентами, но не удалять их (#наше)'), ('manage_supplier_accounts', 'Пользователь может управлять аккаунтами контрагентов (личными кабинетами) (#наше)'), ('delete_suppliers', 'Пользователь может удалять контрагентов (#наше)')], 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.CreateModel(
            name='SupplierCabinetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_id', models.CharField(max_length=16, unique=True, verbose_name='ID кабинета')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_cabinet', to='main.supplier')),
            ],
            options={
                'verbose_name': 'Ссылка на личный кабинет контрагента',
                'verbose_name_plural': 'Ссылки на личные кабинеты контрагентов',
            },
        ),
    ]
