# Generated by Django 3.2.1 on 2024-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_guestcabinetlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transport',
            field=models.CharField(blank=True, max_length=64, verbose_name='Транспорт'),
        ),
    ]
