# Generated by Django 3.2.1 on 2024-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_trip_start_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='route',
            name='transport',
            field=models.CharField(blank=True, max_length=64, verbose_name='Транспорт'),
        ),
    ]
