# Generated by Django 3.2.1 on 2024-03-18 19:52

from django.db import migrations, models
import main.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_route_transport_start_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.utils.file_upload_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='tripworker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.utils.file_upload_path, verbose_name='Фото'),
        ),
    ]
