# Generated by Django 3.2.1 on 2024-04-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_route_and_tripworker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='short_description',
            field=models.CharField(blank=True, max_length=512, verbose_name='Краткое описание'),
        ),
    ]
