# Generated by Django 3.2.1 on 2024-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_trip_default_prepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='actual_address',
            field=models.CharField(blank=True, max_length=512, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='agency',
            name='legal_address',
            field=models.CharField(blank=True, max_length=512, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='agency',
            name='requisites',
            field=models.TextField(blank=True, verbose_name='Реквизиты'),
        ),
    ]
