# Generated by Django 3.2.1 on 2024-05-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_draftcontractpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencySocialNetworkContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=512, verbose_name='Аккаунт')),
                ('social_network', models.CharField(choices=[(None, '(Выберите социальную сеть)'), ('VK', 'ВКонтакте'), ('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('SKYPE', 'Skype'), ('INSTAGRAM', 'Instagram'), ('OPEN_LINE', 'Открытая линия'), ('TELEGRAM', 'Telegram'), ('OTHER', 'Другое')], max_length=16, verbose_name='Социальная сеть')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_network_contacts', to='main.agency')),
            ],
            options={
                'verbose_name': 'Аккаунт агентства в соц. сети',
                'verbose_name_plural': 'Аккаунты агентств в соц. сетях',
            },
        ),
        migrations.AddConstraint(
            model_name='agencysocialnetworkcontact',
            constraint=models.UniqueConstraint(fields=('agency', 'social_network', 'account'), name='main_agencysocialnetworkcontact_is_unique'),
        ),
    ]
