# Generated by Django 3.2.1 on 2024-05-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_social_network_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='group_chat_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на группу в WhatsApp'),
        ),
    ]
