# Generated by Django 3.2.1 on 2024-05-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_trip_group_chat_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='yandex_metrics_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID счётчика в Яндекс Метрике'),
        ),
    ]
