# Generated by Django 3.2.1 on 2024-05-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_agency_yandex_metrics_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeparturePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=32, verbose_name='Выезд из')),
                ('departure_address', models.CharField(max_length=128, verbose_name='Место сбора')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_points', to='main.agency')),
            ],
            options={
                'verbose_name': 'Пункт отправления',
                'verbose_name_plural': 'Пункты отправления',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_points',
            field=models.ManyToManyField(blank=True, related_name='trips', to='main.DeparturePoint'),
        ),
        migrations.AddField(
            model_name='tripcompany',
            name='departure_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_companies', to='main.departurepoint'),
        ),
        migrations.AddConstraint(
            model_name='departurepoint',
            constraint=models.UniqueConstraint(fields=('agency', 'departure_city', 'departure_address'), name='main_departurepoint_name_is_unique'),
        ),
    ]
