# Generated by Django 3.2.1 on 2024-05-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_departure_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_supplier_cabinet_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить кабинет контрагента (и самозапись)'),
        ),
    ]
