# Generated by Django 3.2.1 on 2024-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_add_agency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_trip_auto_update_schedule_enabled',
            field=models.BooleanField(default=False, verbose_name='Показывать галочку для автоматического обновления услуг и дней из шаблона'),
        ),
    ]
